### ISSUE TITLE
Error Encountered When Loading Meta-Llama-3-8B Model

### ISSUE THREAD

**Issue by woreom** [matthew-pisano/UniversalModels#1]
Hello,

First, thank you for maintaining such an excellent repository! I have been using the code from [Bergeron](https://github.com/matthew-pisano/Bergeron) and appreciate all the hard work that has gone into it.

**Issue:**
I am attempting to perform inference using the `meta-llama/Meta-Llama-3-8B` model. However, when I try to load the model as the primary model, I encounter the following error:

```
>>> python evaluate.py respond "mundane" --primary 'meta-llama/Meta-Llama-3-8B' --secondary 'meta-llama/Meta-Llama-3-8B'

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to ###
Login successful
[ INFO Bergeron @ 16:59:11 ] Begin respond at 2024-08-04 20:59:11.199571 UTC
[ INFO Bergeron @ 16:59:11 ] Primary model: meta-llama/Meta-Llama-3-8B
[ INFO Bergeron @ 16:59:11 ] Secondary model: meta-llama/Meta-Llama-3-8B
[ INFO UniversalModels @ 16:59:11 ] Setting random seed to 62
FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|██████████████████| 4/4 [00:04<00:00,  1.13s/it]
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'PreTrainedTokenizerFast'. 
The class this function is called from is 'LlamaTokenizer'.
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/mnt/j/My Drive/Bergeron/evaluate.py", line 532, in <module>
    raise e
  File "/mnt/j/My Drive/Bergeron/evaluate.py", line 529, in <module>
    main()
  File "/mnt/j/My Drive/Bergeron/evaluate.py", line 501, in main
    main_model = load_main_model(args.primary, args.secondary, action, model_src)
  File "/mnt/j/My Drive/Bergeron/evaluate.py", line 399, in load_main_model
    return Bergeron.from_model_names(primary_model_name, secondary_model_name, primary_model_src=model_src, secondary_model_src=model_src)
  File "/mnt/j/My Drive/Bergeron/src/framework/bergeron.py", line 57, in from_model_names
    primary = Primary.from_model_name(primary_model_name, model_src=primary_model_src)
  File "/mnt/j/My Drive/Bergeron/src/framework/primary.py", line 28, in from_model_name
    return cls(p_model_info)
  File "/mnt/j/My Drive/Bergeron/src/framework/primary.py", line 15, in __init__
    self.model, self.tokenizer = pretrained_from_info(model_info)
  File "envs/hug/lib/python3.10/site-packages/universalmodels/interface.py", line 166, in pretrained_from_info
    return model, model_info.tokenizer_class.from_pretrained(model_info.pretrained_model_name_or_path)
  File "envs/hug/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
  File "envs/hug/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2311, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "envs/hug/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 169, in __init__
    self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
  File "envs/hug/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 196, in get_spm_processor
    tokenizer.Load(self.vocab_file)
  File "envs/hug/lib/python3.10/site-packages/sentencepiece/__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "envs/hug/lib/python3.10/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
```

**Steps to Reproduce:**
1. Clone the Bergeron repository: `git clone https://github.com/matthew-pisano/Bergeron.git`
2. Navigate to the cloned directory: `cd Bergeron`
3. Install the required dependencies: `pip install -r requirements.txt`
4. Load the `meta-llama/Meta-Llama-3-8B` model for inference using the provided scripts: 
`python evaluate.py respond "mundane" --primary 'meta-llama/Meta-Llama-3-8B' --secondary 'meta-llama/Meta-Llama-3-8B'`.

**Minimal Step to Reproduce.**
```
from dataclasses import dataclass
from transformers import LlamaTokenizer, LlamaForCausalLM

from universalmodels import ModelInfo, pretrained_from_info, model_info_from_name, ModelSrc

@dataclass
class model_info:
    pretrained_model_name_or_path = "meta-llama/Meta-Llama-3-8B"
    model_src = ModelSrc('auto')
    model_class = LlamaForCausalLM
    tokenizer_class = LlamaTokenizer
    model_task = "conversation"
    _fp_precision = 16


model_name = "meta-llama/Meta-Llama-3-8B"
model, tokenizer = pretrained_from_info(model_info(), )
```

Please let me know if there are any workarounds or additional steps I can take to resolve this issue. I'm looking forward to your guidance and help.

Thank you!

**Comment by woreom** [comment]
*Update: Duck tape patch*
In `interface.py` line 167, modify the code:

```
# return model, model_info.tokenizer_class.from_pretrained(model_info.pretrained_model_name_or_path)
model = AutoModelForCausalLM.from_pretrained(model_info.pretrained_model_name_or_path, torch_dtype = "auto").to('cuda')
tokenizer = AutoTokenizer.from_pretrained(model_info.pretrained_model_name_or_path, torch_dtype = "auto")
return model, tokenizer
```

But I guess it still loads the model 3 time

**Comment by woreom** [comment]
*Update: Bug Fix*
In `interface.py` line 118, modify the code:

```
tokenizer_class = LlamaTokenizer if target_model_name.startswith("meta-llama/Llama-2") else AutoTokenizer
model_class = LlamaForCausalLM if target_model_name.startswith("meta-llama/Llama-2") else AutoModelForCausalLM
```
